# Generated by Django 5.0.1 on 2024-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_is_vendor_userprofile_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
