# Generated by Django 5.0.1 on 2024-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sketh', 'Sketh'), ('waiting for approval', 'Waiting for approval'), ('active', 'Activated'), ('disable', 'Disable'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
