# Generated by Django 5.0.1 on 2024-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumb_image'),
        ),
    ]
