# Generated by Django 5.0.1 on 2024-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_payable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
