# Generated by Django 5.0.1 on 2024-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_order_total_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
